### ISSUE TITLE
No Example Provided

### ISSUE THREAD

**Issue by IAmNatch** [mjurczyk/quixel-to-three#1]
Could you provide an example of a basic Three.js object utilizing these conversions?

That would be a big help!

**Comment by mjurczyk** [comment]
Good idea - I'll try to add a sample demo today.

**Comment by IAmNatch** [comment]
Thanks a lot! I'm happy to help with documentation, but I was not able to
get things working on my end when testing.

**Comment by mjurczyk** [comment]
What do you think about explanation like [this](https://github.com/mjurczyk/quixel-to-three#usage-with-threejs) ? Would it be ok 🤔 ?

**Comment by IAmNatch** [comment]
@mjurczyk I think the demo you provided is fantastic. I love the working codepen as well. 

I'd be interested to see how polished / close to the Quixel Example images the code could be brought to with further processing, but you've definitely already gone above and beyond in providing a great starting point. This has been a big help! 

Thanks a lot!
